site_name: Open Data Contract Standard
repo_url: https://github.com/bitol-io/open-data-contract-standard
repo_name: open-data-contract-standard

plugins:
  - open-in-new-tab
  - search

theme:
  name: material
  logo: img/Bitol_Logo_icon_color.svg
  favicon: img/Bitol_Logo_icon_color.svg
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - navigation.path
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - toc.integrate
    - toc.follow
  palette:
    scheme: slate
  icon:
    repo: fontawesome/brands/git-alt

nav:
  - Home: 'index.md'
  - Standard: 'standard.md'
  - Examples: 'examples/index.md'
  - Contributing: 'contributing.md'

extra:
  social:
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/aidaug/shared_invite/zt-2d6ypx776-YGqtXwlSlCANhn2EWDmNGQ
    - icon: fontawesome/brands/github
      link: https://github.com/bitol-io
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/bitol-io/
  version:
    provider: mike

markdown_extensions:
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences